## CPSC 483-01 Project 5
***
**Name:** Tianzheng Li <br><br>
*All 9 experiments are functional and completed*

*There is an issue where the SVM is unable to fit the data with the dummy data of all 0s, as it only contains one class*

# 1. Download files
***
The data that will be used is `bank-additional.csv`

# 2. read_csv()
***
The data is read, with `;` as the separator

In [1]:
import pandas as pd

# Read data
data = pd.read_csv('bank-additional.csv', sep = ';')
display(data)

age          job  marital          education default  housing     loan  \
0      30  blue-collar  married           basic.9y      no      yes       no   
1      39     services   single        high.school      no       no       no   
2      25     services  married        high.school      no      yes       no   
3      38     services  married           basic.9y      no  unknown  unknown   
4      47       admin.  married  university.degree      no      yes       no   
...   ...          ...      ...                ...     ...      ...      ...   
4114   30       admin.  married           basic.6y      no      yes      yes   
4115   39       admin.  married        high.school      no      yes       no   
4116   27      student   single        high.school      no       no       no   
4117   58       admin.  married        high.school      no       no       no   
4118   34   management   single        high.school      no      yes       no   

        contact month day_of_week  ...  campaign  pdays  previous  \
0      cellular   may         fri  ...         2    999         0   
1     telephone   may         fri  ...         4    999         0   
2     telephone   jun         wed  ...         1    999         0   
3     telephone   jun         fri  ...         3    999         0   
4      cellular   nov         mon  ...         1    999         0   
...         ...   ...         ...  ...       ...    ...       ...   
4114   cellular   jul         thu  ...         1    999         0   
4115  telephone   jul         fri  ...         1    999         0   
4116   cellular   may         mon  ...         2    999         1   
4117   cellular   aug         fri  ...         1    999         0   
4118   cellular   nov         wed  ...         1    999         0   

         poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0     nonexistent         -1.8          92.893          -46.2      1.313   
1     nonexistent          1.1          93.994          -36.4      4.855   
2     nonexistent          1.4          94.465          -41.8      4.962   
3     nonexistent          1.4          94.465          -41.8      4.959   
4     nonexistent         -0.1          93.200          -42.0      4.191   
...           ...          ...             ...            ...        ...   
4114  nonexistent          1.4          93.918          -42.7      4.958   
4115  nonexistent          1.4          93.918          -42.7      4.959   
4116      failure         -1.8          92.893          -46.2      1.354   
4117  nonexistent          1.4          93.444          -36.1      4.966   
4118  nonexistent         -0.1          93.200          -42.0      4.120   

      nr.employed   y  
0          5099.1  no  
1          5191.0  no  
2          5228.1  no  
3          5228.1  no  
4          5195.8  no  
...           ...  ..  
4114       5228.1  no  
4115       5228.1  no  
4116       5099.1  no  
4117       5228.1  no  
4118       5195.8  no  

[4119 rows x 21 columns]

# 3. Preprocessing data
***
The data is turned into a dummy, and the `duration` and `y_yes` columns are removed

In [2]:
# Convert to dummy
data_d = pd.get_dummies(data)

# Remove unnecessary columns
data_d = data_d.drop('duration', 1)

target = []
for i in range(len(data_d)):
    target.append(data_d['y_yes'][i])
    
data_d = data_d.drop('y_yes', 1)

display(data_d)

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0      30         2    999         0          -1.8          92.893   
1      39         4    999         0           1.1          93.994   
2      25         1    999         0           1.4          94.465   
3      38         3    999         0           1.4          94.465   
4      47         1    999         0          -0.1          93.200   
...   ...       ...    ...       ...           ...             ...   
4114   30         1    999         0           1.4          93.918   
4115   39         1    999         0           1.4          93.918   
4116   27         2    999         1          -1.8          92.893   
4117   58         1    999         0           1.4          93.444   
4118   34         1    999         0          -0.1          93.200   

      cons.conf.idx  euribor3m  nr.employed  job_admin.  ...  month_sep  \
0             -46.2      1.313       5099.1           0  ...          0   
1             -36.4      4.855       5191.0           0  ...          0   
2             -41.8      4.962       5228.1           0  ...          0   
3             -41.8      4.959       5228.1           0  ...          0   
4             -42.0      4.191       5195.8           1  ...          0   
...             ...        ...          ...         ...  ...        ...   
4114          -42.7      4.958       5228.1           1  ...          0   
4115          -42.7      4.959       5228.1           1  ...          0   
4116          -46.2      1.354       5099.1           0  ...          0   
4117          -36.1      4.966       5228.1           1  ...          0   
4118          -42.0      4.120       5195.8           0  ...          0   

      day_of_week_fri  day_of_week_mon  day_of_week_thu  day_of_week_tue  \
0                   1                0                0                0   
1                   1                0                0                0   
2                   0                0                0                0   
3                   1                0                0                0   
4                   0                1                0                0   
...               ...              ...              ...              ...   
4114                0                0                1                0   
4115                1                0                0                0   
4116                0                1                0                0   
4117                1                0                0                0   
4118                0                0                0                0   

      day_of_week_wed  poutcome_failure  poutcome_nonexistent  \
0                   0                 0                     1   
1                   0                 0                     1   
2                   1                 0                     1   
3                   0                 0                     1   
4                   0                 0                     1   
...               ...               ...                   ...   
4114                0                 0                     1   
4115                0                 0                     1   
4116                0                 1                     0   
4117                0                 0                     1   
4118                1                 0                     1   

      poutcome_success  y_no  
0                    0     1  
1                    0     1  
2                    0     1  
3                    0     1  
4                    0     1  
...                ...   ...  
4114                 0     1  
4115                 0     1  
4116                 0     1  
4117                 0     1  
4118                 0     1  

[4119 rows x 63 columns]

# 4. Classifiers
***
SVM had the highest accuracy for both training and test set

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

# Split into training and test data
X_train, X_test = train_test_split(data_d, test_size = 0.2)
y_train, y_test = train_test_split(target, test_size = 0.2)

In [4]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Training
# ===================================
# GNB
train_gnb = GaussianNB()
train_gnb.fit(X_train, y_train)
print("Training set")
print("=================")
print("GNB: " + str(train_gnb.score(X_train, y_train)))

# KNN
train_knn = KNeighborsClassifier()
train_knn.fit(X_train, y_train)
print("KNN: " + str(train_knn.score(X_train, y_train)))

# SVM
train_svm = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))
train_svm.fit(X_train, y_train)
print("SVM: " + str(train_svm.score(X_train, y_train)))

# Testing
# ===================================
# GNB
test_gnb = GaussianNB()
test_gnb.fit(X_test, y_test)
print("\nTesting set")
print("=================")
print("GNB: " + str(test_gnb.score(X_test, y_test)))

# KNN
test_knn = KNeighborsClassifier()
test_knn.fit(X_test, y_test)
print("KNN: " + str(test_knn.score(X_test, y_test)))

# SVM
test_svm = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))
test_svm.fit(X_test, y_test)
print("SVM: " + str(test_svm.score(X_test, y_test)))

Training set
GNB: 0.28861911987860395
KNN: 0.8910470409711685
SVM: 0.8892261001517451

Testing set
GNB: 0.25728155339805825
KNN: 0.8980582524271845
SVM: 0.9004854368932039


# 5. Target values
***
In the training set, the target (`y_yes`) contains almost 90% 0s, meaning most people do not subscribe to the term deposit. If no customers subscribed then the accuracy would be much lower because we would not know how to classify those that would subscribe.

In [5]:
y_yes0 = 0
y_yes1 = 0
for i in range(len(y_train)):
    if y_train[i] == 0:
        y_yes0 += 1
    else:
        y_yes1 += 1
        
print("In a training set of length " + str(len(y_train)) + 
      " there are [" + str(y_yes0) + "] 0s and [" + str(y_yes1) + "] 1s")    

In a training set of length 3295 there are [2926] 0s and [369] 1s


# 6. AUC
***
The AUC of the training data with `LogisticRegression` is `0.538`, which was not unable to calculated with just a single class (dummy with just 0s).

In [6]:
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

dumb_train = np.zeros_like(y_train)
dumb_matrix = confusion_matrix(y_train, dumb_train)
print(dumb_matrix)

lr = LogisticRegression(solver="liblinear", random_state=0).fit(X_train, y_train)
print("AUC: " + str(roc_auc_score(y_train, lr.decision_function(X_train))))

[[2926    0]
 [ 369    0]]
AUC: 0.5548470214708983


# 7. AUC for all classifiers
***
The AUC for all 3 of the classifiers (SVM does not work with only 1 class of just 0s) shwos that the they are all roughly the same. The best classifier (SVM) does have the best accuracy but that may not be necessarily the case.

In [7]:
# GNB
dumb_gnb = GaussianNB()
dumb_gnb.fit(X_train, dumb_train)
print("GNB AUC: " + str(roc_auc_score(y_train, dumb_gnb.predict(X_train))))
print(confusion_matrix(y_train, dumb_gnb.predict(X_train)))
print()

# KNN
dumb_knn = KNeighborsClassifier()
dumb_knn.fit(X_train, dumb_train)
print("KNN AUC: " + str(roc_auc_score(y_train, dumb_knn.predict(X_train))))
print(confusion_matrix(y_train, dumb_knn.predict(X_train)))
print()

# SVM
dumb_svm = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))
dumb_svm.fit(X_train, y_train)
print("SVM AUC: " + str(roc_auc_score(y_train, dumb_svm.predict(X_train))))
print(confusion_matrix(y_train, dumb_svm.predict(X_train)))

GNB AUC: 0.5
[[2926    0]
 [ 369    0]]

KNN AUC: 0.5
[[2926    0]
 [ 369    0]]

SVM AUC: 0.505420054200542
[[2926    0]
 [ 365    4]]


# 8. Random Oversampling
***
Using `RandomOverSampler` we get a data set that is resampled and fitted

In [8]:
from imblearn.over_sampling import RandomOverSampler 

ros = RandomOverSampler(random_state=2021-4-22)
X_res, y_res = ros.fit_resample(X_train, y_train)

# 9. Classifier Scores and AUC
***
KNN now has the highest score of `0.901`, almost double the other two at around 0.5 for both. <br/>
The AUCs are roughly the same but the confusion matrix shows their splits are different.

In [9]:
# GNB
train_gnb2 = GaussianNB()
train_gnb2.fit(X_res, y_res)
print("Training set scores")
print("=================")
print("GNB: " + str(train_gnb2.score(X_res, y_res)))

# KNN
train_knn2 = KNeighborsClassifier()
train_knn2.fit(X_res, y_res)
print("KNN: " + str(train_knn2.score(X_res, y_res)))

# SVM
train_svm2 = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))
train_svm2.fit(X_res, y_res)
print("SVM: " + str(train_svm.score(X_res, y_res)))

Training set scores
GNB: 0.5452836637047164
KNN: 0.8942241968557758
SVM: 0.5047846889952153


In [10]:
dumb_train2 = np.zeros_like(y_res)

In [11]:
# GNB
dumb_gnb2 = GaussianNB()
dumb_gnb2.fit(X_res, dumb_train2)
print("Training set AUC")
print("=================")
print("GNB AUC: " + str(roc_auc_score(y_res, dumb_gnb2.predict(X_res))))
print(confusion_matrix(y_res, dumb_gnb2.predict(X_res)))
print()

# KNN
dumb_knn2 = KNeighborsClassifier()
dumb_knn2.fit(X_res, dumb_train2)
print("KNN AUC: " + str(roc_auc_score(y_res, dumb_knn2.predict(X_res))))
print(confusion_matrix(y_res, dumb_knn2.predict(X_res)))
print()

# SVM
dumb_svm2 = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))
dumb_svm2.fit(X_res, y_res)
print("SVM AUC: " + str(roc_auc_score(y_res, dumb_svm2.predict(X_res))))
print(confusion_matrix(y_res, dumb_svm2.predict(X_res)))

Training set AUC
GNB AUC: 0.5
[[2926    0]
 [2926    0]]

KNN AUC: 0.5
[[2926    0]
 [2926    0]]

SVM AUC: 0.8725222146274778
[[2334  592]
 [ 154 2772]]
